Repository dalek-cryptography/bulletproofs, pull requests merged in 2018-04, with the labels that each got.

#58 ProofTranscript: use stock `tiny-keccak` crate with duplex construction
  Cargo.toml
  src/proof_transcript.rs
Labels: PTAL

#61 Add a `SinglePartyAggregator` and refactor test code
  src/aggregated_range_proof/dealer.rs
  src/aggregated_range_proof/messages.rs
  src/aggregated_range_proof/mod.rs
Labels: PTAL, api

#63 Keep dealer parameters internal to the dealer state
  src/aggregated_range_proof/dealer.rs
  src/aggregated_range_proof/mod.rs
Labels: PTAL, api

#72 Add aggregate proof benchmarks
  benches/bulletproofs.rs
Labels: PTAL, optimization

#79 Fix the build and add benches to CI
  .travis.yml
  benches/bulletproofs.rs
Labels: PTAL, bug

#78 try using travis's rust cargo cache
  .travis.yml
Labels: PTAL
