Repository dalek-cryptography/bulletproofs, pull requests merged in 2018-11, with the labels that each got.

#199 Update dependencies
  Cargo.toml
  src/generators.rs
  src/lib.rs
  src/range_proof/party.rs
Labels: PTAL

#207 Merge main into circuit
  Cargo.toml
  README.md
  benches/r1cs.rs
  docs/cs-proof.md
  docs/notes.md
  src/constraint_system/assignment.rs
  src/constraint_system/mod.rs
  src/constraint_system/prover.rs
  src/constraint_system/tests.rs
  src/constraint_system/verifier.rs
  src/generators.rs
  src/inner_product_proof.rs
  src/lib.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
  src/transcript.rs
  src/util.rs
Labels: PTAL

#211 Eliminate R1CS facade
  src/constraint_system/mod.rs
  src/lib.rs
  src/r1cs/assignment.rs
  src/r1cs/constraint_system.rs
  src/r1cs/linear_combination.rs
  src/r1cs/mod.rs
  src/r1cs/proof.rs
  src/r1cs/prover.rs
  src/r1cs/tests.rs
  src/r1cs/verifier.rs
Labels: PTAL, api, circuits

#212 Split notes into multiple files
  docs/notes-intro.md
  docs/notes-ipp.md
  docs/notes-r1cs.md
  docs/notes-rp.md
  docs/notes.md
  src/lib.rs
Labels: PTAL, circuits, docs, rubberstamp

#109 Circuit work tracker [WIP]
  .travis.yml
  Cargo.toml
  README.md
  benches/r1cs.rs
  benches/range_proof.rs
  docs/aggregation-api.md
  docs/cs-proof.md
  docs/notes-intro.md
  docs/notes-ipp.md
  docs/notes-r1cs.md
  docs/notes-rp.md
  rust-toolchain
  src/errors.rs
  src/generators.rs
  src/inner_product_proof.rs
  src/lib.rs
  src/r1cs/constraint_system.rs
  src/r1cs/linear_combination.rs
  src/r1cs/mod.rs
  src/r1cs/proof.rs
  src/r1cs/prover.rs
  src/r1cs/tests.rs
  src/r1cs/verifier.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
  src/transcript.rs
  src/util.rs
Labels: circuits
