Repository dalek-cryptography/bulletproofs, pull requests merged in 2018-07, with the labels that each got.

#104 enable dalek slack integration
  .travis.yml
Labels: PTAL, rubberstamp

#105 Update pinned Rust version
  rust-toolchain
Labels: PTAL, rubberstamp

#99 Canonical serialization format for RangeProof
  src/inner_product_proof.rs
  src/lib.rs
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
  src/util.rs
Labels: PTAL, optimization

#111 Merge main into circuit
  src/circuit_proof/mod.rs
  src/inner_product_proof.rs
  src/lib.rs
  src/range_proof/dealer.rs
  src/range_proof/mod.rs
  src/util.rs
Labels: PTAL, circuits

#113 Use CompressedRistretto in CircuitProof
  src/circuit_proof/mod.rs
Labels: PTAL, circuits

#114 Add CONTRIBUTING.md and check fmt in CI
  .travis.yml
  CONTRIBUTING.md
Labels: PTAL, rubberstamp

#101 Arithmetic circuit notes
  docs/notes.md
Labels: PTAL, circuits

#121 Enforce that `n` is 0 or power of 2 for IPP
  src/inner_product_proof.rs
Labels: PTAL

#120 Enforce lengths of inputs to circuit proofs
  src/circuit_proof/mod.rs
Labels: PTAL, circuits

#106 R1CS circuit frontend
  src/circuit_proof/mod.rs
  src/circuit_proof/r1cs.rs
Labels: PTAL, circuits

#123 Pad circuits when creating them from `r1cs` format
  src/circuit_proof/r1cs.rs
Labels: PTAL, circuits

#124 Add failure-based error types.
  Cargo.toml
  src/errors.rs
  src/inner_product_proof.rs
  src/lib.rs
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
Labels: api

#127 Update to dalek 0.19
  Cargo.toml
  benches/bulletproofs.rs
  src/inner_product_proof.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
  src/util.rs
Labels: optimization

#130 Make separate circuit module
  src/circuit_proof/circuit.rs
  src/circuit_proof/mod.rs
  src/circuit_proof/r1cs.rs
Labels: PTAL, circuits
