Repository dalek-cryptography/bulletproofs, pull requests merged in 2018-10, with the labels that each got.

#177 Streamline range proof Party/Dealer APIs
  benches/bulletproofs.rs
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
Labels: PTAL

#182 Add bulletproofs diagram to the README
  README.md
  docs/assets/bulletproofs-diagram.png
Labels: PTAL

#179 Add API docs for circuit code
  Cargo.toml
  README.md
  benches/bulletproofs.rs
  docs/aggregation-api.md
  docs/assets/aggregated-range-proof.sketch
  docs/notes.md
  docs/range-proof-protocol.md
  rust-toolchain
  src/circuit_proof/assignment.rs
  src/circuit_proof/mod.rs
  src/circuit_proof/prover.rs
  src/circuit_proof/verifier.rs
  src/errors.rs
  src/generators.rs
  src/inner_product_proof.rs
  src/lib.rs
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
Labels: api, circuits, docs

#187 Add R1CS benchmark (shuffle)
  Cargo.toml
  benches/r1cs.rs
  benches/range_proof.rs
Labels: PTAL, circuits

#184 Improving circuit notes
  docs/circuit-proof-math.md
  docs/cs-proof.md
  src/circuit_proof/mod.rs
  src/circuit_proof/prover.rs
Labels: PTAL, circuits

#159 Combine multiscalar mults in circuit verifier
  src/circuit_proof/prover.rs
  src/circuit_proof/verifier.rs
Labels: PTAL

#189 Add doctest for r1cs proof
  src/lib.rs
Labels: PTAL, circuits, docs

#183 Clear secrets when dropped
  Cargo.toml
  src/lib.rs
  src/range_proof/party.rs
  src/util.rs
Labels: PTAL

#191 Clarify aggregation of RPs and CSs in the notes
  docs/aggregation-api.md
  docs/notes.md
Labels: PTAL, docs

#190 Efficient padding of the constraint system to a power-of-two multipliers
  docs/cs-proof.md
  src/circuit_proof/mod.rs
  src/circuit_proof/prover.rs
  src/circuit_proof/tests.rs
  src/circuit_proof/verifier.rs
Labels: PTAL, docs, optimization

#193 Zero heap allocations in the circuit code
  src/circuit_proof/assignment.rs
  src/circuit_proof/prover.rs
  src/range_proof/party.rs
  src/util.rs
Labels: PTAL

#195 Revert unsound attempt to clear secrets on the stack
  src/circuit_proof/prover.rs
  src/range_proof/party.rs
Labels: PTAL

#103 Use {lo,hi} instead of {L,R} where appropriate in notes module.
  docs/notes.md
Labels: docs
