Repository dalek-cryptography/bulletproofs, pull requests merged in 2018-09, with the labels that each got.

#140 Proving and verifying directly on R1CS instance
  rust-toolchain
  src/circuit_proof/assignment.rs
  src/circuit_proof/mod.rs
  src/circuit_proof/r1cs.rs
  src/errors.rs
  src/generators.rs
  src/inner_product_proof.rs
  src/lib.rs
  src/range_proof/mod.rs
Labels: PTAL, circuits

#143 Update R1CS API
  src/circuit_proof/r1cs.rs
Labels: PTAL, circuits

#145 Eliminate the `circuit` module and prove directly from the constraint data
  src/circuit_proof/circuit.rs
  src/circuit_proof/mod.rs
  src/circuit_proof/r1cs.rs
  src/transcript.rs
Labels: PTAL, circuits

#152 Add a notion of capacity to the Generators struct
  rust-toolchain
  src/errors.rs
  src/generators.rs
  src/inner_product_proof.rs
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
Labels: PTAL, api, circuits

#154 Replace constant terms in LC by constant Variables
  src/circuit_proof/mod.rs
  src/circuit_proof/prover.rs
  src/circuit_proof/verifier.rs
Labels: PTAL, circuits

#158 ConstraintSystems hold onto generators struct
  rust-toolchain
  src/circuit_proof/mod.rs
  src/circuit_proof/prover.rs
  src/circuit_proof/verifier.rs
  src/range_proof/mod.rs
Labels: PTAL, api, circuits

#160 Verification should operate on compressed points
  rust-toolchain
  src/circuit_proof/prover.rs
  src/circuit_proof/verifier.rs
Labels: PTAL, api, circuits

#165 Use Merlin v0.4
  Cargo.toml
  src/range_proof/mod.rs
Labels: PTAL

#169 Add documentation and doctests to rangeproof code.
  Cargo.toml
  README.md
  benches/bulletproofs.rs
  docs/aggregation-api.md
  docs/notes.md
  docs/range-proof-protocol.md
  src/errors.rs
  src/lib.rs
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
Labels: docs

#176 Readme links
  Cargo.toml
  README.md
Labels: PTAL

#175 Update diagram with BitChallenge/BitCommitment terms
  docs/aggregation-api.md
  docs/assets/aggregated-range-proof.sketch
  src/range_proof/dealer.rs
  src/range_proof/messages.rs
  src/range_proof/mod.rs
  src/range_proof/party.rs
Labels: PTAL

#178 Optimize inner-product prover by inlining adjustment scalars
  src/inner_product_proof.rs
  src/range_proof/dealer.rs
Labels: PTAL, optimization

#166 Implement PartialEq for Assignment
  src/circuit_proof/assignment.rs
Labels: PTAL, api, circuits
